### ISSUE TITLE
gap between title and rating

### ISSUE THREAD

**Issue by ondrejbima** [bartolomesoriano/skin.amber#11]
There is a quite big gap between title and rating in List View, is it bug or purpose?
Version ee6f4e202a196e7195f45c309fae9d13ba833afb
![2020-04-14 15-25-53](https://user-images.githubusercontent.com/5797/79230033-4e143d00-7e64-11ea-8c63-4745966bfda6.png)

**Comment by bartolomesoriano** [comment]
@beam , it is on purpose.  The second label (rating in your screenshot) can be many other things, including date added, which takes up more space.  If you want a longer title, you can disable the second label in list views in the skin settings (Settings, Skin Settings, Media Views).
