### ISSUE TITLE
Titles missing from icon view

### ISSUE THREAD

**Issue by rolandas-valantinas** [bartolomesoriano/skin.amber#12]
After last update titles are missing from icon view in add-ons and YouTube plugin
![15909234469677395733172054881859](https://user-images.githubusercontent.com/6222540/83350956-cf9e2c80-a337-11ea-8264-dc524c38e7d1.jpg)

**Comment by bartolomesoriano** [comment]
When did you update from GitHub? Yesterday afternoon? The latest from GitHub (Leia) should be fine.  Please download and test again.  Thanks.

**Comment by rolandas-valantinas** [comment]
I'm on 3.2.86, it is the latest version 
https://github.com/bartolomesoriano/repo.amber/commits?author=bartolomesoriano

**Comment by bartolomesoriano** [comment]
Thanks.  Download the latest from the skin's Leia branch in GitHub, not from the Amber repo.  The latest commit is https://github.com/bartolomesoriano/skin.amber/commit/9ef29d527efe60e877f47c53234a6fbd7f54233b.  I still have not uploaded my latest changes/fixes to the Amber repos.

**Comment by rolandas-valantinas** [comment]
Thank you very much for the quick fix. I'll try this once I get a chance 👍

**Comment by rolandas-valantinas** [comment]
Tested and commit works as expected. Thank you 👍
