### ISSUE TITLE
Power > Quit does not quit

### ISSUE THREAD

**Issue by bernd-wechner** [bartolomesoriano/skin.amber#13]
This I suspect has been a bug for a long time. I thought it a Kodi bug but it's never been so much of a problem to bother reporting as my HTPC runs 24/7 anyhow and Kodi runs on it.

But upgraded to Matrix recently and ended up with the default skin for a while. Was pleased that Quit worked. Then installed Amber fro Matrix and suddenly it doesn't work again. It locks up Kodi, to be sure, but does not quit. It just locks it up and I need to kill it forcefully (kill -9). I attach a debbug log taken as follows:

1. Enable debug logging
2. Power > Quit

[kodi (power-quit - amber skin).log](https://github.com/bartolomesoriano/skin.amber/files/4802376/kodi.power-quit.-.amber.skin.log)

And system details are:

```
$ inxi -F --no-host
System:    Kernel: 5.3.0-59-generic x86_64 bits: 64 Console: tty 0 Distro: Linux Mint 19.3 Tricia 
Machine:   Type: Desktop Mobo: Compulab model: fitlet2 v: 1.21 serial: <root required> UEFI: American Megatrends 
           v: FLT2.MBM2.0.46.01.00 date: 09/26/2018 
CPU:       Topology: Quad Core model: Intel Celeron J3455 bits: 64 type: MCP L2 cache: 1024 KiB 
           Speed: 1400 MHz min/max: 800/2300 MHz Core speeds (MHz): 1: 1342 2: 1398 3: 1350 4: 1326 
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Display: server: X.org 1.19.6 driver: modesetting unloaded: fbdev,vesa tty: 124x68 
           Message: Advanced graphics data unavailable in console. Try -G --display 
Audio:     Device-1: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster driver: snd_hda_intel 
           Device-2: Texas Instruments Speakers type: USB driver: snd-usb-audio 
           Sound Server: ALSA v: k5.3.0-59-generic 
Network:   Device-1: Intel Wireless 8260 driver: iwlwifi 
           IF: wlp1s0 state: down mac: d0:c6:37:d1:e7:dc 
           Device-2: Intel I211 Gigabit Network driver: igb 
           IF: enp2s0 state: down mac: 00:01:c0:25:42:5e 
           Device-3: Intel I211 Gigabit Network driver: igb 
           IF-ID-1: eno1 state: up speed: 1000 Mbps duplex: full mac: 00:01:c0:25:42:61 
Drives:    Local Storage: total: 119.04 GiB used: 56.39 GiB (47.4%) 
           ID-1: /dev/sda model: Maximus 128G size: 119.04 GiB 
Partition: ID-1: / size: 117.03 GiB used: 56.39 GiB (48.2%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 42.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 231 Uptime: 7d 3h 44m Memory: 7.60 GiB used: 2.99 GiB (39.3%) Init: systemd runlevel: 5 
           Shell: bash inxi: 3.0.32 
```

**Comment by bartolomesoriano** [comment]
@bernd-wechner , thanks for bringing this to my attention.  There is indeed an issue with some of the power menu options in Amber for Matrix, including Quit.

I have already uploaded the fix to GitHub.  If after downloading the latest from the master branch you are still experiencing the issue, unfortunately, you will have to delete the Amber-related skinshortcuts settings.  Go to userdata\addon_data\script.skinshortcuts and delete anything that has amber in the file name.

**Comment by bernd-wechner** [comment]
That was fast, and must have been easy, I'll check the commit out to learn something about it too.

**Comment by bernd-wechner** [comment]
Wow, that was a trivial fix. Out of interest, what am I to make of the fork tree on this skin. I ask  because maintenance of this sort of stuff gets confusing over time and yours is a fork of @jester-xbmc jester-xbmc's repo which is a fork of pecinko's repo abd I'm wondering which one trickles into the formal Kodi skins repo. pecinko seems to have fallen inactive 2 years ago, jester too, and you have a a lot of peer forks. But I'm reading yours as the Matrix fork and as active. If so, over time, I might like to add some features to Amber and I'm big on offering PR's up the food chain so to speak to the point where it enters the productions stream (Kodi's skin repo) and isn't just a pet project among a gazillion of them that dies in time due to divergence from the live branch and neglect.

**Comment by bartolomesoriano** [comment]
@bernd-wechner , I am the official maintainer for Amber.  At some point soon I will be updating the Kodi repo with the latest versions for Leia and Matrix.  I welcome any PRs you might want to submit.  After all, that's what Kodi is about, community :)

**Comment by bernd-wechner** [comment]
Great. I think it might be an idea some time to clean up the repo fork tree then for clarity. What some folk do is just start a whole new repo with anew name. I often see 2 or ng used or a new relase tag. 

Something kike skin.amber2 or skin.amber.ng or skin.amber.matrix, just some thoughts. I can even remain skin.amber but if created fresh not as a form, and with a README stating this is the currently maintained repo that pushes to Kodi skin repos, then the fork tree would look cleaner, 

My main interest in tweaking Amber is rearranging the Fullscreen playback a bit so it renders better on our TV ;-). I imagine it would be activated with a setting for people who need larger fonts on Fullscreen (are running it on a TV jukebox and can't read the writing from standard spots in the room ;-). But some layout tweaks to suit our Jukebox use case I have in mind too.
