### ISSUE TITLE
Strange resizing jitter on Matrix main menu backgrounds

### ISSUE THREAD

**Issue by twig** [bartolomesoriano/skin.amber#18]
I noticed the main menu backgrounds are stretched funny on my ultra-wide resolution.
It seems fine when going into settings.

* Kodi 19 (Matrix beta2)
* Amber v3.4.7
* Screen size 2560x1080p
* Windows 10 x64

Recording of the issue here when returning from settings: https://imgur.com/a/htjkkO9

**Comment by bartolomesoriano** [comment]
@twig , I just fixed this.  Please test and let me know.  Thanks.

**Comment by twig** [comment]
the commit looks ok,

But then again I'm not well versed enough in skin xml syntax to know if this applies to all items in home screen or not.
I assume it does 🤞

**Comment by bartolomesoriano** [comment]
@twig , yes it does. The background image on all home menu items will no be scaled, just like it is for the windows other than home.

**Comment by twig** [comment]
awesome, thanks for fixing it!
