### ISSUE TITLE
shelves loading /

### ISSUE THREAD

**Issue by nrpetonr** [bartolomesoriano/skin.amber#19]
flawless on leia, some problems on matrix RC1 (coreelec on odroid N2),  i assume related to shelves settings.
very often after reboot, skin fails to load any shelves  (for media, for addons, etc.). if this happens, also many other settings (e.g. shutdown, corelec settings, etc.)  are not able to be opened from gui. actually it is vissible also in the log.

if i switch to other skin, it also can't load the widgets until i reboot, it starts to work afterwards. I can than change back to amber and it will work as well until next reboot. If reboot again to test if amber survives w/o problem, the problemm will be back, e.g. 7 out of 10 reboots.

log: https://drive.google.com/file/d/1y9I8LzeFyO5eETEKPU0HjLRvh-3897kN/view?usp=sharing

**Comment by freaktabnl** [comment]
![image](https://user-images.githubusercontent.com/36622939/106111176-05581700-614c-11eb-82e7-86f1085a9dc8.png)

**Comment by nrpetonr** [comment]
finally fixed it, i assume it was [script.skinvariable  ](https://forum.kodi.tv/showthread.php?tid=353811&page=3) related
reinstalled with matrix version, plus installed other dependent addons shown under amber settings (though i do not think this is related) and no more problem to load the shelves.
