### ISSUE TITLE
Fanart media view only showing home screen background in netflix style

### ISSUE THREAD

**Issue by tapwizard** [bartolomesoriano/skin.amber#21]
Hello, using the latest version of skin I notice that when using the fanart media view (netflix style) when scrolling through movies there is no picture for movie displayed, just the background in main menu. If I switch to fanart (show info) then the panel shows a box with picture for movie highlighted. I have checked all settings with the skin found in kodi repo and they are exactly the same. Thanks

**Comment by bartolomesoriano** [comment]
@tapwizard , just to confirm.  You do have the setting "Show Fanart Background in Sub Windows" set to "Yes"? If so, can you please post a screenshot of what you are seeing? Thanks.

**Comment by tapwizard** [comment]
Yes I had that setting checked, but was not showing. I ended up doing a fresh install of everything and now with same settings its working, go figure. Thanks for your help.

**Comment by bartolomesoriano** [comment]
@tapwizard , I am glad you got it sorted.
