### ISSUE TITLE
Artwork Beef widget integration problematic?

### ISSUE THREAD

**Issue by inspector71** [bartolomesoriano/skin.amber#23]
UPDATE: OK, this is weird. The `poster.jpg` files in the movie folder on disk corresponding to broken thumbails, are all zero bytes ... Hmmm, wonder how they get that way.

----

Thank you immensely for all your hard work on the best, by far, Kodi skin.

Almost have a perfect (for my needs) config in place. Only artwork was mediocre so trying Artwork Beef for first time.

Played around a lot in settings though Artwork Beef options are almost infinite. Good but overwhelming? 

Just cannot get Artwork Beef and Amber playing nicely together. Resulting in this:

https://i.imgur.com/Ey2btSw.jpg

New movies do not automatically display posters and/or some other artwork types. Movies that have artwork in that screenshot may, or may not, have been manually manipulated into place and, honestly, do not recall the process but I can try to document if it would help. Otherwise, anyone have a magic settings combo that works like a charm?

Some details:

1. Movie source `Choose information provider` set to `Local information only` AKA, AFAIK, `.nfo` files
2. `Local information only` is fed by Radarr / Sonarr using, `AFAIK`, tmdb.
3. LibreELEC `9.2.6` / `18.9 (18.9.0) leia_pi4_18.9-Leia` so no Matrix influence
4. AFAIK not a caching thing in that after days, the texture cache never catches up
5. Can use `texturecache.py` if helps though Artwork Beef seems to have a similar / identical, action?
6. [Example `.nfo` file](https://pastebin.com/AYjBq1u8) for one of the broken thumbnail items in the above screenshot
7. Amber version: `3.2.123`
7. Arwork Beef version:`0.28.5`

Anything else I can do to help, please let me know. I can edit XML and use Reload Skin Cache if it helps.

**Comment by bartolomesoriano** [comment]
@inspector71 , are you still having this issue? Please let me know.  Thanks.

**Comment by inspector71** [comment]
> @inspector71 , are you still having this issue? Please let me know. Thanks.

Yes, the issue is still happening as I have not debugged it any further and thus the cause of the zero-byte posters is still a mystery.

Unsure where to start debugging actually. Not seeing the issue with TV Shows so perhaps the issue is Radarr-specific.

Might try uninstalling Artwork Beef for starters.

Otherwise, debugging ideas would are welcome :)

**Comment by inspector71** [comment]
Maybe this issue could be marked: 'Resolved - invalid' because the issue I seemed to be experiencing does not seem to be an Artwork Beef issue ^

1. Uninstalled Artwork Beef
2. Reset (hard) LibreELEC
3. Re-installed Amber
4. Attempted to restore a backup (***very*** messy procedure)
5. SFTP `sources.xml`; `mediasources.xml`; `Set Content`: `Movies`, `Local Information Only`, `Movies are in separate folders that match the movie title`

_Still had the same problem._

1. Reset (hard) LibreELEC
2. SFTP `sources.xml`; `mediasources.xml`; `Set Content`: `Movies`, `Local Information Only`, `Movies are in separate folders that match the movie title`

_Still the problem persists!_

1. Check actual movie locations for `poster.jpg` where posters are not working ...

_ZERO BYTE FILES!_

2. Delete zero-byte `poster.jpg` files
3. `Refresh & Scan` each movie (individually, grrr) in Radarr
4. `Refresh` movies in Kodi (individually, grrr)
5. Wait for cache to kick in (grrr)

### Problem: solved!

^

* Yet to determine how the zero-byte `poster.jpg` files were created. Artwork Beef ***might*** yet be the culprit!
* Also, if the actual `poster.jpg` files were zero-byte in length, how could I `Refresh` and/or `Choose Art`; `Poster`; then `Current Art` was empty/null ... but `Remote Art` always shows a legitimate poster thumbnail I can set as a functioning poster!?
