### ISSUE TITLE
Incorrect season ordering on View_600_Triple

### ISSUE THREAD

**Issue by roidy** [bartolomesoriano/skin.amber#29]
https://github.com/bartolomesoriano/skin.amber/blob/f12ce78d90d0afccd6d54edbada6fd602578d06e/1080i/View_600_Triple.xml#L540

Been playing around with this type of view in my skin and found that sorting seasons by year can give incorrect results when the show contains a "Specials" season. The correct sort order should be seasonnumber

`<content target="video" sortby="seasonnumber" sortorder="ascending">$INFO[Container(600).ListItem.FolderPath]</content> `

**Comment by bartolomesoriano** [comment]
@roidy , thank you! i had not noticed this.  I will change the sort order.
